name: SBB GitOps CI/CD Pipeline

on:
  push:
    branches: [ "main" ] 
    paths-ignore:        
      - 'cn-board-manifests/**'
      - 'README.md'

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  BACKEND_IMAGE_NAME: jangswan/cn_board_app
  FRONTEND_IMAGE_NAME: jangswan/cn_board_nginx
  MANIFEST_PATH: cn-board-menifests

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.generate_tag.outputs.sha }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Generate Short SHA for Tag
        id: generate_tag
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Backend (Gradle)
        run: |
          gradle clean bootJar -x test --no-daemon -p ./app

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build & Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: true
          tags: |
            ${{ env.BACKEND_IMAGE_NAME }}:${{ steps.generate_tag.outputs.sha }}
            ${{ env.BACKEND_IMAGE_NAME }}:latest

      - name: Build & Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./nginx-project
          push: true
          tags: |
            ${{ env.FRONTEND_IMAGE_NAME }}:${{ steps.generate_tag.outputs.sha }}
            ${{ env.FRONTEND_IMAGE_NAME }}:latest

  update-manifest:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }} 

      - name: Update Kubernetes Manifests
        run: |
          NEW_TAG=${{ needs.build-and-push.outputs.image_tag }}
          
          sed -i "s|image: .*${{ env.BACKEND_IMAGE_NAME }}:.*|image: ${{ env.BACKEND_IMAGE_NAME }}:$NEW_TAG|g" ${{ env.MANIFEST_PATH }}/sbb-backend-deploy.yml
          
          sed -i "s|image: .*${{ env.FRONTEND_IMAGE_NAME }}:.*|image: ${{ env.FRONTEND_IMAGE_NAME }}:$NEW_TAG|g" ${{ env.MANIFEST_PATH }}/sbb-frontend-deploy.yml
          
          cat ${{ env.MANIFEST_PATH }}/sbb-backed-deploy.yml | grep Image:
          cat ${{ env.MANIFEST_PATH }}/sbb-frontend-deploy.yml | grep Image:

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          if [[ -n $(git status -s) ]]; then
            git add ${{ env.MANIFEST_PATH }}/*.yaml
            git commit -m "Update K8s manifests to tag: ${{ needs.build-and-push.outputs.image_tag }}"
            git push
          else
            echo "No changes to commit."
          fi
