name: CN-SBB GitHub Actions CI Pipeline

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'cn-board-manifests/**'
      - 'README.md'

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  BACKEND_IMAGE_NAME: jangswan/cn_board_app
  FRONTEND_IMAGE_NAME: jangswan/cn_board_nginx
  MANIFEST_PATH: cn-board-manifests

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.generate_tag.outputs.sha }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Generate Short SHA for Tag
        id: generate_tag
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Backend (Gradle)
        run: |
          chmod +x ./app/gradlew
          ./app/gradlew clean bootJar -x test --no-daemon -p ./app

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build & Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: true
          tags: |
            ${{ env.BACKEND_IMAGE_NAME }}:${{ steps.generate_tag.outputs.sha }}
            ${{ env.BACKEND_IMAGE_NAME }}:latest

      - name: Build & Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./nginx-project
          push: true
          tags: |
            ${{ env.FRONTEND_IMAGE_NAME }}:${{ steps.generate_tag.outputs.sha }}
            ${{ env.FRONTEND_IMAGE_NAME }}:latest

      - name: Print Image Tag
        run: |
          echo "Docker Image Build and Push Succeed."
          echo "New Image Tag: ${{ steps.generate_tag.outputs.sha }}"
